DEEPSEEK_API_KEY = "sk-844f7121c69e471da4933807b23a1b01"  # Votre clé réelle
APP_PASSWORD = "Ametis2025"  # Mot de passe personnalisable
# .streamlit/secrets.toml
FORCE_SQLITE = "true"
SQLITE_TIMEOUT = "30"
